#!/bin/bash

echo "Running test files"
make
cd io
echo "Running app1.txt"
./file < ../app/app1.txt

echo "Running app2.txt"
./file < ../app/app1.txt

echo "Running the app itself to freely explore"
./file